export const PendingContextType = {
  CLARIFY_TRANSACTION_TYPE: 'CLARIFY_TRANSACTION_TYPE',
  CLARIFY_REPORT_PERIOD: 'CLARIFY_REPORT_PERIOD',
  CLARIFY_AMOUNT: 'CLARIFY_AMOUNT',
  CLARIFY_CATEGORY: 'CLARIFY_CATEGORY',
  LOW_CONFIDENCE_CREATE: 'LOW_CONFIDENCE_CREATE',
  CONFIRM_AUDIO_TRANSCRIPT: 'CONFIRM_AUDIO_TRANSCRIPT',
  CONFIRM_RECEIPT_OCR: 'CONFIRM_RECEIPT_OCR',
} as const;

export type PendingContextTypeValue = (typeof PendingContextType)[keyof typeof PendingContextType];
