export const UserIntent = {
  CREATE_EXPENSE: 'CREATE_EXPENSE',
  CREATE_INCOME: 'CREATE_INCOME',
  CREATE_TRANSFER: 'CREATE_TRANSFER',
  GET_MONTH_SUMMARY: 'GET_MONTH_SUMMARY',
  GET_CATEGORY_BREAKDOWN: 'GET_CATEGORY_BREAKDOWN',
  GET_TOP_EXPENSES: 'GET_TOP_EXPENSES',
  GET_RECURRING_EXPENSES: 'GET_RECURRING_EXPENSES',
  GET_LAST_TRANSACTIONS: 'GET_LAST_TRANSACTIONS',
  UPDATE_LAST_TRANSACTION_AMOUNT: 'UPDATE_LAST_TRANSACTION_AMOUNT',
  UPDATE_LAST_TRANSACTION_CATEGORY: 'UPDATE_LAST_TRANSACTION_CATEGORY',
  DELETE_LAST_TRANSACTION: 'DELETE_LAST_TRANSACTION',
  HELP: 'HELP',
  UNKNOWN: 'UNKNOWN',
} as const;

export type UserIntentType = (typeof UserIntent)[keyof typeof UserIntent];

export const ParseStatus = {
  OK: 'OK',
  NEEDS_CONFIRMATION: 'NEEDS_CONFIRMATION',
  FAILED: 'FAILED',
} as const;

export type ParseStatusType = (typeof ParseStatus)[keyof typeof ParseStatus];
